### ISSUE TITLE
Size of smd Resistors and leds 

### ISSUE THREAD

**Issue by ABXYog** [Kekule-OXC/OXC_Port_LEDs#1]
Really trying to figure out what size smd and leds to use with them.

**Comment by Kekule-OXC** [comment]
resistors are 0603, and the LED are 0805.   you have to choose the resistor values based on the forward voltage of your LED.

**Comment by DizzGaming** [comment]
Hi there, resistors are 0603, and the LED's are 0805. Do you have any recommended values for these? I will be purchasing them all new and was wondering what values work best? Cheers, Dizz.

**Comment by Kekule-OXC** [comment]
you set the value of the resistor from the specs of the LED.  use an online LED resistor calculator if you are unsire
